baseurl = "https://www.shubhamkukreti.com"
title = "Shubham Kukreti"
author = "Shubham Kukreti"
canonifyurls = true
languagecode = "en"
theme = "hugo-black-and-light-theme"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Shubham Kukreti"
  disableWebFonts = false

[[menu.main]]
    name = "Blogs"
    url = "/blogs/"
    weight = 1
[[menu.main]]
    name = "Gallery"
    url = "/gallery/"
    weight = 2
[[menu.main]]
    name = "Socials"
    url = "/social/"
    weight = 3