baseurl = "https://www.shubhamkukreti.com"
title = "Shubham Kukreti"
author = "Shubham Kukreti"
canonifyurls = true
languagecode = "en"
theme = "hugo-black-and-light-theme"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[permalinks]
posts = ":slug/"

[params]
  sitename = "Shubham Kukreti"
  disableWebFonts = false

[[menu.main]]
    name = "Twitter"
    url  = "https://twitter.com/ShubhamKukretii"
[[menu.main]]
    name = "Github"
    url  = "https://github.com/KukretiShubham"
